#!/bin/bash

    ./BenchMarkSch1.py $1 10
    ./BenchMarkSch1.py $1 100
    ./BenchMarkSch1.py $1 1000
    ./BenchMarkSch1.py $1 10000

    ./BenchMarkSch2.py $1 10
    ./BenchMarkSch2.py $1 100
    ./BenchMarkSch2.py $1 1000
    ./BenchMarkSch2.py $1 10000

    ./BenchMarkSch2b.py $1 10 10
    ./BenchMarkSch2b.py $1 100 10
    ./BenchMarkSch2b.py $1 1000 100
    ./BenchMarkSch2b.py $1 10000 100